var AppConstants = {
    STORE_CHANGE: "CHANGE",
    STORE_ERROR: "ERROR",
    LOCATION_ADD: 1,
    LOCATION_EDIT: 2,
    LOCATION_DELETE: 3,
    LOCATION_LIST: 4,
    USER_LOGIN: 5,
    USER_REGISTER: 6,
    LOCATION_BY_ID: 7,
    RETRIEVED: 8,
    CREATED: 9,
    UPDATED: 10,
    DELETED: 11,
    USER_LOGOUT: 12,
    RESOURCE_ADD: 13,
    RESOURCE_EDIT: 14,
    RESOURCE_DELETE: 15,
    RESOURCE_LIST: 16,
    ACTIVITY_ADD: 17,
    ACTIVITY_DELETE: 18,
    RESOURCES_TOP_FIVE:19
};

module.exports = AppConstants;